MR-1
PMazarovich/React-Burgerz-Yandex pull request #1
Opened 2023-05-06 15:51 UTC by PMazarovich

2023-05-06 16:40 UTC, PMazarovich commented
Компоненты FoodContainer кликабельные - левый клик увеличит счетчик на 1, правый клик уменьшит на 1

2023-05-06 16:45 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая декомпозиция компонентов
- Проект соответствует макету

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- элементам списка нужно задавать key, он помогает понять реакту, что элементы перемещаются в списке
- У всех компонентов с пропсами должны быть `propTypes`

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-06 16:45 UTC, andryxxa93 commented on src/components/AppHeader/header.js
> +class Header extends React.Component {
**Можно лучше**
сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков

2023-05-06 16:45 UTC, andryxxa93 commented on src/components/BurgerIngredients/burger-ingredients.js
> +                            {dataStub.filter(x => x.type === "bun").map(x => <FoodContainer key={x._id} name={x.name}
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```
const buns = data.filter((item) => item.type === 'bun');
const mains = data.filter((item) => item.type === 'main');
const sauces = data.filter((item) => item.type === 'sauce');

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в самом jsx

2023-05-07 10:06 UTC, andryxxa93 commented
Промежуточная работа принята, вы можете приступать к финальному этапу сдачи работы.

2023-05-07 16:40 UTC, merged