State to redux, introduce DND
PMazarovich/React-Burgerz-Yandex pull request #4
Opened 2023-06-18 10:59 UTC by PMazarovich

Не получилось сделать внутреннюю сортировку, если возможно, покажите, пожалуйста, в моем проекте, где и как ее следовало бы сделать 

Еще вопрос: Почему-то redux-logger дважды выводит в консоль события (читал, что это нормальное поведение), это совсем неудобно и приходится его отключать и смотреть всё в ReduxDevTools. Может быть есть возможность как-то это поведение исправить?
Спасибо!

2023-06-18 12:08 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- По макету у булок должна быть приписка `(верх)` и `(низ)`.

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- В приложении не должно быть никаких логов: <https://disk.yandex.com/i/gR32nEAYeeYZPQ>;

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- По чек-листу требуется реализовать:

  - Пользователь может сортировать элементы в конструкторе перетаскиванием. Сортировать элементы типа bun перетаскиванием нельзя;

- Желательно, чтобы изначально не было булок, и пользователь сам выбирал её. Если булок нет, то заказ оформить нельзя (кнопка не активна).

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/WSkoH3G-C4e_AA>;

- В компоненте AppHeader поправьте семантику, иконка и текст должны быть обёрнуты в ссылку, а не в `div`;

- <https://disk.yandex.com/i/SgJVemNTYRfrcg> - Вёрстка модального окна заказа не соответствует макету.

- <https://disk.yandex.com/i/fRXWTJ9QApB33g> - Вёрстка модального окна ингредиента не соответствует макету.

- У вас возникает ошибка, при открытии модального окна заказа: <https://disk.yandex.com/i/tWkyr4cEPLrTJw>;

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-06-18 12:08 UTC, ArslanMustafin commented on src/store/reducers/BurgerConstructorSlice.js
> +            },
**Надо исправить:**
 
Не стоит хранить `dragging` в сторе, лучше использовать обычный `useState` или `useContext` (но там не большая вложенность, поэтому всё же лучше `useState`), в род компоненте, т.к. нигде кроме конструктора это больше использоваться не будет.

2023-06-18 12:08 UTC, ArslanMustafin commented on src/store/reducers/BurgerConstructorSlice.js
> +                state.ingredients.push({uuid: uuidv4(), ingredientId: action.payload.ingredientId})
**Надо исправить:**

Редьюсер должен быть чистой функцией, поэтому генерировать id нужно в экшене. Для этого в redux-toolkit есть специальный action-creator: https://redux-toolkit.js.org/api/createSlice#customizing-generated-action-creators

2023-06-18 12:08 UTC, ArslanMustafin commented on src/store/reducers/BurgerConstructorSlice.js
> +                    console.log(current(state.ingredients[i]))
**Надо исправить:**

в приложении не должно быть никаких логов.

2023-06-18 12:08 UTC, ArslanMustafin commented on src/store/reducers/BurgerConstructorSlice.js
> +                }
**Можно лучше:**

попробуйте тут убирать элемент через filter.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2023-06-18 12:08 UTC, ArslanMustafin commented on src/components/BurgerConstructor/burger-constructor.js
>          </div>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

Все стили задавайте через классы и гляньте библиотеку https://www.npmjs.com/package/classnames, она вам очень может помочь.

2023-06-18 12:08 UTC, ArslanMustafin commented on src/components/BurgerConstructor/burger-constructor.js
**Можно лучше:**

Для подсчёта стоимости лучше использовать `useMemo`.

2023-06-18 12:08 UTC, ArslanMustafin commented on src/components/BurgerConstructor/burger-constructor.js
> +    summ = summ + chosenBun.price*2
**Можно лучше:**

Для подсчёта стоимости лучше использовать `useMemo`.

2023-06-18 12:10 UTC, ArslanMustafin commented
> Не получилось сделать внутреннюю сортировку, если возможно, покажите, пожалуйста, в моем проекте, где и как ее следовало бы сделать
> 
> Еще вопрос: Почему-то redux-logger дважды выводит в консоль события (читал, что это нормальное поведение), это совсем неудобно и приходится его отключать и смотреть всё в ReduxDevTools. Может быть есть возможность как-то это поведение исправить? Спасибо!

Добрый день. По поводу сортировки, обратитесь за помощью к наставнику. 
А двойные логи это результат `StrictMode`.
https://react.dev/reference/react/StrictMode

2023-06-18 21:32 UTC, PMazarovich commented
Спасибо за ревью!
Сейчас пока внутренняя сортировка еще не сделана, остальные ошибки исправлены. 
orderConfirmed окно починил, теперь там номер заказа

2023-06-19 10:48 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/pHkPh5EeOPT5iw> - нужно поправить внешний вид ссылок, ещё раз сверьтесь с макетом.

- <https://disk.yandex.com/i/SgJVemNTYRfrcg> - Вёрстка модального окна заказа не соответствует макету. Нужно добавить паддинги, заменить иконку, убрать надпись `order confirmed`.

- <https://disk.yandex.com/i/fRXWTJ9QApB33g> - Вёрстка модального окна ингредиента не соответствует макету. Нужно добавить паддинги, уменьшить шрифт у характеристик, убрать надпись `Ingredient details:`.

- По чек-листу требуется реализовать:

  - Пользователь может сортировать элементы в конструкторе перетаскиванием. Сортировать элементы типа bun перетаскиванием нельзя;

### **Сделает работу лучше:**

- В приложении не должно быть никаких логов: <https://disk.yandex.com/i/gR32nEAYeeYZPQ>, в том числе и логов от редакса);

2023-06-19 10:48 UTC, ArslanMustafin commented on src/index.tsx
> +                     style={{position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)'}}/>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-06-19 10:50 UTC, ArslanMustafin commented
> Спасибо за ревью! Сейчас пока внутренняя сортировка еще не сделана, остальные ошибки исправлены. orderConfirmed окно починил, теперь там номер заказа

Самое главное сделаете сортировку элементов, а остальное как получится)) Сортировку нужно обязательно сделать, т.к. это требование чек-листа)

2023-06-19 23:55 UTC, PMazarovich commented
Сортировка добавлена

2023-06-20 15:03 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все обязательные замечания были исправлены;

### **Сделает работу лучше:**

- <https://disk.yandex.com/i/pHkPh5EeOPT5iw> - нужно поправить внешний вид ссылок, ещё раз сверьтесь с макетом.

- <https://disk.yandex.com/i/SgJVemNTYRfrcg> - Вёрстка модального окна заказа не соответствует макету. Нужно добавить паддинги, заменить иконку, убрать надпись `order confirmed`.

- <https://disk.yandex.com/i/fRXWTJ9QApB33g> - Вёрстка модального окна ингредиента не соответствует макету. Нужно добавить паддинги, уменьшить шрифт у характеристик, убрать надпись `Ingredient details:`.

- В приложении не должно быть никаких логов: <https://disk.yandex.com/i/gR32nEAYeeYZPQ>, в том числе и логов от редакса);

2023-06-20 15:04 UTC, ArslanMustafin commented
> Сортировка добавлена

Круто 🔥, работу принял) но постарайтесь к следующему заданию исправить моменты с версткой и консолью) Удачи!

2023-06-20 15:19 UTC, PMazarovich commented
@ArslanMustafin спасибо за ревью!

2023-06-20 15:56 UTC, merged