Routing initial
PMazarovich/React-Burgerz-Yandex pull request #5
Opened 2023-07-30 20:13 UTC by PMazarovich

Здравствуйте!
Это первая часть проекта, сделано до пункта 5 - Получение и обновление информации о пользователе.
Проверьте, пожалуйста,  правильно ли сделана "первая" часть этой проектной работы.
Есть вопрос, описан в коде src/components/Login/login.js:20
Спасибо!

2023-07-30 20:49 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая работа с инпутами
- Правильно используете запросы

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- При попытке открыть страницу профиля не авторизованным юзером - должен происходить редирект на страницу логина
- Не авторизованный юзер не должен иметь возможность сделать заказ
- Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.
- Роута logout быть не должно, после логаута нужно переводить или на главную или на страницу логина
- Ссылки в хедере не работают
- В проекте необходимо реализовать компонент ProtectedRoute - который будет "защищать" роуты.
- Необходимо реализовать остальной функционал из тех-задания.

Напомню, что если у вас что-то не получается вы всегда можете обратиться к своему наставнику.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-30 20:49 UTC, andryxxa93 commented on src/components/App/App.jsx
> +                    <Route path="/login" element={<Login />}/>   {/* по пути /login лежит страница LoginPage */}
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-07-30 20:49 UTC, andryxxa93 commented on src/components/Login/login.js
> +            const data = await auth.signIn({email: login, password: password});
Не очень понятен вопрос - после авторизации происходит редирект - всё правильно.

2023-08-16 00:30 UTC, PMazarovich commented
@andryxxa93 Спасибо за ревью!
email - HeNZPQZyofer8K63YovU1BsKl8fGqCkd@test.com
пароль - HeNZPQZyofer8K63YovU1BsKl8fGqCkd
(для проверки функционала, если вдруг будет нужно)

2023-08-16 16:25 UTC, andryxxa93 commented
**Необходимо исправить**

- Страница конструктора должна быть общедоступной. Т.е. на неё могут заходить авторизованные и не авторизованные юзеры.
- В запрос на восстановление пароля не попадает токен введеный в инпут.

<img width="525" alt="Снимок экрана 2023-08-16 в 19 21 16" src="https://github.com/PMazarovich/React-Burgerz-Yandex/assets/60173362/08a06231-a255-49d1-ba29-846139263eb5">

 - Вам нужно использовать в хедере не Link а NavLink и через className задавать активность. https://reactrouter.com/en/main/components/nav-link
 - При изменении данных юзера на странице профиля должны появляться кнопки "Отмена" и "Сохранить", чтобы можно было отправить измененные данные на сервер.

2023-08-17 16:14 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-17 19:42 UTC, merged