Sprint 4/step 1
PMazarovich/React-Burgerz-Yandex pull request #7
Opened 2023-09-18 19:32 UTC by PMazarovich

Typescript

2023-09-18 20:25 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая типизация проекта
- Использовали встроенный тип `Response`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Избавьтесь от ts-ignore в app.tsx. Для этого вам нужно изменить типизацию ProtectedRouteElement. Используйте не  `ReactNode`. а `React.ReactElement` и `JSX.Element`
- В проекте присутствует несколько any от которых можно без проблем избавиться.
- Используйте в `parseJsonFromResponse` вместо any дженерики
- Типизируйте используемые файлы в директории `utils`
- типографика текста не соответвует макету, используйте стили из библиотеки согласно макету

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-18 20:25 UTC, andryxxa93 commented on src/components/BurgerConstructor/burger-constructor.tsx
> +function ConstructorElementWrapper({
**Надо исправить**

типографика текста не соответвует макету, используйте стили из библиотеки согласно макету

2023-09-21 18:40 UTC, PMazarovich commented
Спасибо за проверку!
Исправил некоторые any, оставил те, которые в store (лектор сказала его не типизировать).
js перевел в ts в utils.
Иcправил стиль constructor (drag icon)

2023-09-22 07:23 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-23 07:42 UTC, merged